	server.port=8082
	
	spring.application.name=order-service
	
	eureka.client.service-url.defaultZone=http://localhost:8761/eureka
	
	eureka.instance.prefer-ip-address=true
	
	management.endpoints.web.exposure.include=health,info,metrics
	management.info.env.enabled=true
	
	info.app.name=Order Service
	info.app.description=Order management microservice
	info.app.version=1.0.0
	
	

	
# ===============================
# Resilience4j Retry
# ===============================
	
resilience4j.circuitbreaker.instances.paymentService.register-health-indicator=true
resilience4j.circuitbreaker.instances.paymentService.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.paymentService.sliding-window-size=20

resilience4j.circuitbreaker.instances.paymentService.failure-rate-threshold=50
	
resilience4j.circuitbreaker.instances.paymentService.minimum-number-of-calls=15
	
resilience4j.circuitbreaker.instances.paymentService.wait-duration-in-open-state=10s
	
resilience4j.circuitbreaker.instances.paymentService.permitted-number-of-calls-in-half-open-state=2
	
resilience4j.circuitbreaker.instances.paymentService.automatic-transition-from-open-to-half-open-enabled=true
	
	
# ===============================
# Resilience4j Retry
# ===============================

resilience4j.retry.instances.paymentService.max-attempts=3

resilience4j.retry.instances.paymentService.wait-duration=1s

# Jitter / randomized wait
resilience4j.retry.instances.paymentService.enable-randomized-wait=true

resilience4j.retry.instances.paymentService.randomized-wait-factor=0.5

# Keep exponential backoff disabled for now
resilience4j.retry.instances.paymentService.enable-exponential-backoff=true
resilience4j.retry.instances.paymentService.exponential-backoff-multiplier=2

# ===============================
# Resilience4j RateLimiter
# ===============================

resilience4j.ratelimiter.instances.paymentService.limit-for-period=10
resilience4j.ratelimiter.instances.paymentService.limit-refresh-period=60s
resilience4j.ratelimiter.instances.paymentService.timeout-duration=0


# ===============================
# Resilience4j Bulkhead - Semaphore
# ===============================

#resilience4j.bulkhead.instances.paymentService.max-concurrent-calls=3
#resilience4j.bulkhead.instances.paymentService.max-wait-duration=5s

# ===============================
# ThreadPool Bulkhead - ThreadPool
# ===============================

resilience4j.thread-pool-bulkhead.instances.paymentService.max-thread-pool-size=3
resilience4j.thread-pool-bulkhead.instances.paymentService.core-thread-pool-size=2
resilience4j.thread-pool-bulkhead.instances.paymentService.queue-capacity=2
resilience4j.thread-pool-bulkhead.instances.paymentService.keep-alive-duration=20s


# ===============================
# Retry logs
# ===============================

logging.level.io.github.resilience4j.retry=DEBUG


# Aspect order
#resilience4j.retry.retry-aspect-order=1
#resilience4j.circuitbreaker.circuit-breaker-aspect-order=2
#resilience4j.ratelimiter.rate-limiter-aspect-order=3
#resilience4j.bulkhead.bulkhead-aspect-order=4